name: cafe_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  go_router: ^13.2.4
  google_maps_flutter: ^2.5.3
  provider: ^6.0.0
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/LOGO_NO-TEXT.png"
